---
- hosts: webservers 
  become: True
  tasks:
    - name: Deploy static website
      copy:
        src: /home/jazeera/work/jazeeraprojects/retail/retail-apigateway-grpc/Dockerfile
        dest: /home/ubuntu
...
